grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 3
    verbose: 2
model_selection:
  module_0:
    class: XGBClassifier
    module: xgboost
    params:
      nthread: 4
      objective: binary:hinge
      learning_rate: 0.05
      max_depth : 6
      min_child_weight : 11
      silent : 
    search_param_grid:
      learning_rate: 
      - 0
      - 0.5
      n_estimators :
      -5
      -50
      -100
  module_1:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      min_samples_leaf: 3
      bootstrap: True
      min_samples_split: 2
      n_estimators: 200
    search_param_grid:
      min_samples_leaf:
      - 1
      - 2
      min_samples_split:
      - 2
      - 5
      - 7
      n_estimators:
      - 200
      - 400
      - 800
      - 1000
      